/* eslint-disable @typescript-eslint/naming-convention */
const tocList = {
  toc_initialize: [
    "api_createagorartcengineex",
    "api_irtcengine_getmediaengine",
    "api_mediaplayercontroller_initialize",
    "api_irtcengine_create",
    "api_createagorartcengine",
    "api_irtcengine_initialize",
    "api_irtcengine_release",
    "api_irtcengine_addlistener",
    "api_irtcengine_removelistener",
    "api_irtcengine_removealllisteners",
    "api_irtcengine_addhandler",
    "api_irtcengine_removehandler",
  ],
  toc_channel: [
    "api_irtcengine_delegate",
    "api_irtcengineex_getuserinfobyuidex",
    "api_irtcengineex_getuserinfobyuseraccountex",
    "api_irtcengine_getuserinfobyuid",
    "api_irtcengine_getuserinfobyuseraccount",
    "api_irtcengine_joinchannel",
    "api_irtcengine_joinchannel2",
    "api_irtcengineex_joinchannelex",
    "api_irtcengine_joinchannelwithuseraccount",
    "api_irtcengine_joinchannelwithuseraccount2",
    "api_irtcengine_joinchannelwithuseraccountex",
    "api_irtcengine_leavechannel",
    "api_irtcengine_leavechannel2",
    "api_irtcengineex_leavechannelex",
    "api_irtcengineex_leavechannelex2",
    "api_irtcengine_preloadchannel",
    "api_irtcengine_preloadchannel2",
    "api_irtcengine_registerlocaluseraccount",
    "api_irtcengine_renewtoken",
    "api_irtcengine_setchannelprofile",
    "api_irtcengine_setclientrole",
    "api_irtcengine_setclientrole2",
    "api_irtcengine_updatechannelmediaoptions",
    "api_irtcengineex_updatechannelmediaoptionsex",
    "api_irtcengine_updatepreloadchanneltoken",
    "callback_irtcengineeventhandler_onclientrolechanged",
    "callback_irtcengineeventhandler_onclientrolechangefailed",
    "callback_irtcengineeventhandler_onerror",
    "callback_irtcengineeventhandler_onjoinchannelsuccess",
    "callback_irtcengineeventhandler_onleavechannel",
    "callback_irtcengineeventhandler_onlocaluserregistered",
    "callback_irtcengineeventhandler_onrejoinchannelsuccess",
    "callback_irtcengineeventhandler_onrequesttoken",
    "callback_irtcengineeventhandler_onrtcstats",
    "callback_irtcengineeventhandler_ontokenprivilegewillexpire",
    "callback_irtcengineeventhandler_onuserinfoupdated",
    "callback_irtcengineeventhandler_onuserjoined",
    "callback_irtcengineeventhandler_onuseroffline",
  ],
  toc_publishnsubscribe: [
    "api_irtcengine_muteallremoteaudiostreams",
    "api_irtcengineex_muteallremoteaudiostreamsex",
    "api_irtcengine_muteallremotevideostreams",
    "api_irtcengineex_muteallremotevideostreamsex",
    "api_irtcengine_mutelocalaudiostream",
    "api_irtcengineex_mutelocalaudiostreamex",
    "api_irtcengine_mutelocalvideostream",
    "api_irtcengineex_mutelocalvideostreamex",
    "api_irtcengine_muteremoteaudiostream",
    "api_irtcengineex_muteremoteaudiostreamex",
    "api_irtcengine_muteremotevideostream",
    "api_irtcengineex_muteremotevideostreamex",
    "api_irtcengine_setremotevideosubscriptionoptions",
    "api_irtcengineex_setremotevideosubscriptionoptionsex",
    "api_irtcengine_setsubscribeaudioallowlist",
    "api_irtcengineex_setsubscribeaudioallowlistex",
    "api_irtcengine_setsubscribeaudioblocklist",
    "api_irtcengineex_setsubscribeaudioblocklistex",
    "api_irtcengine_setsubscribevideoallowlist",
    "api_irtcengineex_setsubscribevideoallowlistex",
    "api_irtcengine_setsubscribevideoblocklist",
    "api_irtcengineex_setsubscribevideoblocklistex",
    "callback_irtcengineeventhandler_onaudiopublishstatechanged",
    "callback_irtcengineeventhandler_onaudiosubscribestatechanged",
    "callback_irtcengineeventhandler_onvideosubscribestatechanged",
  ],
  toc_audio_basic: [
    "api_irtcengine_enableaudioqualityindication",
    "api_irtcengine_adjustuserplaybacksignalvolume",
    "api_irtcengineex_adjustuserplaybacksignalvolumeex",
    "api_irtcengine_disableaudio",
    "api_irtcengine_enableaudio",
    "api_irtcengine_enableaudiovolumeindication",
    "api_irtcengineex_enableaudiovolumeindicationex",
    "api_irtcengine_setaudioprofile",
    "api_irtcengine_setaudioprofile2",
    "api_irtcengine_setaudioscenario",
    "api_irtcengine_setaudiosessionoperationrestriction",
    "callback_irtcengineeventhandler_onactivespeaker",
    "callback_irtcengineeventhandler_onaudioquality",
    "callback_irtcengineeventhandler_onaudiovolumeindication",
    "callback_irtcengineeventhandler_onfirstlocalaudioframepublished",
    "callback_irtcengineeventhandler_onfirstremoteaudiodecoded",
    "callback_irtcengineeventhandler_onfirstremoteaudioframe",
    "callback_irtcengineeventhandler_onlocalaudiostatechanged",
    "callback_irtcengineeventhandler_onlocalaudiostats",
    "callback_irtcengineeventhandler_onremoteaudiostatechanged",
    "callback_irtcengineeventhandler_onremoteaudiostats",
    "callback_irtcengineeventhandler_onremoteaudiotransportstats",
    "callback_irtcengineeventhandler_onusermuteaudio",
  ],
  toc_audio_capture: [
    "api_irtcengine_adjustloopbacksignalvolume",
    "api_irtcengine_adjustrecordingsignalvolume",
    "api_irtcengine_enableinearmonitoring",
    "api_irtcengine_enableinearmonitoring2",
    "api_irtcengine_enablelocalaudio",
    "api_irtcengine_enableloopbackrecording",
    "api_irtcengineex_enableloopbackrecordingex",
    "api_irtcengine_muterecordingsignal",
    "api_irtcengine_setinearmonitoringvolume",
  ],
  toc_audio_effect: [
    "api_irtcengine_getaudioeffectmanager",
    "api_irtcengine_setadvancedaudiooptions",
    "api_irtcengine_setainsmode",
    "api_irtcengine_setaudioeffectparameters",
    "api_irtcengine_setaudioeffectpreset",
    "api_irtcengine_setlocalvoiceequalization",
    "api_irtcengine_setlocalvoiceformant",
    "api_irtcengine_setlocalvoicepitch",
    "api_irtcengine_setlocalvoicereverb",
    "api_irtcengine_setvoicebeautifierparameters",
    "api_irtcengine_setvoicebeautifierpreset",
    "api_irtcengine_setvoiceconversionpreset",
  ],
  toc_sound_position: [
    "api_irtcengine_enablesoundpositionindication",
    "api_irtcengineex_setremotevoicepositionex",
    "api_irtcengine_setremotevoiceposition",
  ],
  toc_spatial_audio: [
    "api_ilocalspatialaudioengine_create",
    "api_ilocalspatialaudioengine_release",
    "api_ilocalspatialaudioengine_updateselftransform",
    "api_irtcengine_getlocalspatialaudioengine",
    "api_ilocalspatialaudioengine_initialize",
    "api_ibasespatialaudioengine_muteallremoteaudiostreams",
    "api_ibasespatialaudioengine_mutelocalaudiostream",
    "api_ibasespatialaudioengine_muteremoteaudiostream",
    "api_ilocalspatialaudioengine_updateremoteposition",
    "api_ibasespatialaudioengine_updateselfposition",
    "api_ibasespatialaudioengine_release",
    "api_ilocalspatialaudioengine_clearremotepositions",
    "api_ilocalspatialaudioengine_removeremoteposition",
    "api_ibasespatialaudioengine_setaudiorecvrange",
    "api_ibasespatialaudioengine_setdistanceunit",
    "api_irtcengine_setheadphoneeqparameters",
    "api_irtcengine_setheadphoneeqpreset",
    "api_ibasespatialaudioengine_setmaxaudiorecvcount",
    "api_ibasespatialaudioengine_setplayerattenuation",
    "api_ilocalspatialaudioengine_setremoteaudioattenuation",
    "api_irtcengine_setremoteuserspatialaudioparams",
    "api_ibasespatialaudioengine_setzones",
    "api_ibasespatialaudioengine_updateplayerpositioninfo",
    "api_irtcengine_enablespatialaudio",
  ],
  toc_audio_raw: [
    "api_imediaengine_unregisteraudioframeobserver",
    "api_irtcengine_unregisteraudioframeobserver",
    "api_imediaengine_registeraudioframeobserver",
    "api_irtcengine_setearmonitoringaudioframeparameters",
    "api_irtcengine_setmixedaudioframeparameters",
    "api_irtcengine_setplaybackaudioframebeforemixingparameters",
    "api_irtcengine_setplaybackaudioframeparameters",
    "api_irtcengine_setrecordingaudioframeparameters",
    "callback_iaudioframeobserverbase_getearmonitoringaudioparams",
    "callback_iaudioframeobserverbase_getmixedaudioparams",
    "callback_iaudioframeobserverbase_getobservedaudioframeposition",
    "callback_iaudioframeobserverbase_getplaybackaudioparams",
    "callback_iaudioframeobserverbase_getrecordaudioparams",
    "callback_iaudioframeobserverbase_onearmonitoringaudioframe",
    "callback_iaudioframeobserverbase_onplaybackaudioframe",
    "callback_iaudioframeobserver_onplaybackaudioframebeforemixing",
    "callback_iaudioframeobserverbase_onrecordaudioframe",
    "callback_iaudioframeobserverbase_onmixedaudioframe",
  ],
  toc_audio_encoded: [
    "api_irtcengine_unregisteraudioencodedframeobserver",
    "callback_iaudioencodedframeobserver_onmixedaudioencodedframe",
    "api_irtcengine_registeraudioencodedframeobserver",
    "callback_iaudioencodedframeobserver_onplaybackaudioencodedframe",
    "callback_iaudioencodedframeobserver_onrecordaudioencodedframe",
  ],
  toc_audio_custom_capturenrendering: [
    "api_irtcengine_setexternalaudiosource",
    "api_irtcengine_pullaudioframe2",
    "api_irtcengine_pushaudioframe2",
    "api_irtcengine_pullplaybackaudioframesamplebufferbylengthinbyte",
    "api_irtcengine_pushexternalaudioframesamplebuffer",
    "api_irtcengine_adjustcustomaudioplayoutvolume",
    "api_irtcengine_adjustcustomaudiopublishvolume",
    "api_imediaengine_createcustomaudiotrack",
    "api_imediaengine_destroycustomaudiotrack",
    "api_irtcengine_enablecustomaudiolocalplayback",
    "api_imediaengine_setexternalaudiosource2",
    "api_imediaengine_pullaudioframe",
    "api_imediaengine_pushaudioframe0",
    "api_imediaengine_setexternalaudiosink",
  ],
  toc_audio_spectrum: [
    "api_irtcengine_registeraudiospectrumobserver",
    "api_irtcengine_unregisteraudiospectrumobserver",
    "api_irtcengine_disableaudiospectrummonitor",
    "api_irtcengine_enableaudiospectrummonitor",
    "callback_iaudiospectrumobserver_onlocalaudiospectrum",
    "callback_iaudiospectrumobserver_onremoteaudiospectrum",
  ],
  toc_video_basic: [
    "api_irtcengine_setvideoprofile",
    "api_irtcengine_setvideoprofile2",
    "api_irtcengine_disablevideo",
    "api_irtcengine_enablelocalvideo",
    "api_irtcengine_enablevideo",
    "api_irtcengine_setvideoencoderconfiguration",
    "api_irtcengineex_setvideoencoderconfigurationex",
    "api_irtcengine_setvideoscenario",
    "api_irtcengine_startpreview",
    "api_irtcengine_startpreview2",
    "api_irtcengine_stoppreview",
    "api_irtcengine_stoppreview2",
    "callback_irtcengineeventhandler_onfirstlocalvideoframe",
    "callback_irtcengineeventhandler_onfirstlocalvideoframepublished",
    "callback_irtcengineeventhandler_onfirstremotevideodecoded",
    "callback_irtcengineeventhandler_onfirstremotevideoframe",
    "callback_irtcengineeventhandler_onlocalvideostatechanged",
    "callback_irtcengineeventhandler_onlocalvideostats",
    "callback_irtcengineeventhandler_onremotevideostatechanged",
    "callback_irtcengineeventhandler_onremotevideostats",
    "callback_irtcengineeventhandler_onremotevideotransportstats",
    "callback_irtcengineeventhandler_onuserenablelocalvideo",
    "callback_irtcengineeventhandler_onuserenablevideo",
    "callback_irtcengineeventhandler_onusermutevideo",
    "callback_irtcengineeventhandler_onvideopublishstatechanged",
    "callback_irtcengineeventhandler_onvideosizechanged",
    "callback_irtcengineeventhandler_onvideostopped",
  ],
  toc_camera_capture: [
    "api_irtcengine_startcameracapture",
    "api_irtcengine_stopcameracapture",
  ],
  toc_screencapture: [
    "api_iscreencapturesourcelist_getcount",
    "api_irtcengine_getscreencapturesources",
    "api_iscreencapturesourcelist_getsourceinfo",
    "api_irtcengine_queryscreencapturecapability",
    "api_iscreencapturesourcelist_release",
    "api_irtcengine_setscreencapturecontenthint",
    "api_irtcengine_setscreencapturescenario",
    "api_irtcengine_startscreencapture",
    "api_irtcengine_startscreencapture2",
    "api_irtcengine_startscreencapturebydisplayid",
    "api_irtcengine_startscreencapturebyscreenrect",
    "api_irtcengine_startscreencapturebywindowid",
    "api_irtcengine_stopscreencapture",
    "api_irtcengine_stopscreencapture2",
    "api_irtcengine_updatescreencapture",
    "api_irtcengine_updatescreencaptureparameters",
    "api_irtcengine_updatescreencaptureregion",
  ],
  toc_snapshot: [
    "api_irtcengine_enablecontentinspect",
    "api_irtcengineex_enablecontentinspectex",
    "api_irtcengine_takesnapshot",
    "api_irtcengineex_takesnapshotex",
    "callback_irtcengineeventhandler_onsnapshottaken",
  ],
  toc_virtualbackground: [
    "api_irtcengine_enablevirtualbackground",
    "api_irtcengine_enablevirtualbackground2",
  ],
  toc_video_enhance_option: [
    "api_irtcengine_setbeautyeffectoptions",
    "api_irtcengine_setbeautyeffectoptions2",
    "api_irtcengine_setcolorenhanceoptions",
    "api_irtcengine_setcolorenhanceoptions2",
    "api_irtcengine_setlowlightenhanceoptions",
    "api_irtcengine_setlowlightenhanceoptions2",
    "api_irtcengine_setvideodenoiseroptions",
    "api_irtcengine_setvideodenoiseroptions2",
  ],
  toc_face_detection: [
    "api_irtcengine_enablefacedetection",
    "callback_irtcengineeventhandler_onfacepositionchanged",
  ],
  toc_watermark: [
    "api_irtcengine_addvideowatermark",
    "api_irtcengine_addvideowatermark2",
    "api_irtcengineex_addvideowatermarkex",
    "api_irtcengine_clearvideowatermarks",
    "api_irtcengineex_clearvideowatermarkex",
  ],
  toc_image_source: ["api_irtcengine_enablevideoimagesource"],
  toc_dual_stream: [
    "api_irtcengine_enabledualstreammode",
    "api_irtcengine_enabledualstreammode3",
    "api_irtcengineex_enabledualstreammodeex",
    "api_irtcengine_setdualstreammode",
    "api_irtcengine_setdualstreammode2",
    "api_irtcengineex_setdualstreammodeex",
    "api_irtcengine_setremotedefaultvideostreamtype",
    "api_irtcengine_setremotevideostreamtype",
    "api_irtcengineex_setremotevideostreamtypeex",
  ],
  toc_local_transcoder: [
    "api_irtcengine_startlocalvideotranscoder",
    "api_irtcengine_stoplocalvideotranscoder",
    "api_irtcengine_updatelocaltranscoderconfiguration",
    "callback_irtcengineeventhandler_onlocalvideotranscodererror",
    "callback_irtcengineeventhandler_ontranscodedstreamlayoutinfo",
  ],
  toc_video_rendering: [
    "api_irtcengine_createrendererview",
    "api_irtcengine_createtextureview",
    "api_irtcengine_setremoterendermode",
    "api_videosurface_setenable",
    "api_videosurface_setforuser",
    "callback_videosurface_ontexturesizemodify",
    "api_irtcengine_destroyrendererbyconfig",
    "api_irtcengine_destroyrendererbyview",
    "api_irtcengine_enableinstantmediarendering",
    "api_irtcengine_setlocalrendermode",
    "api_irtcengine_setlocalrendermode2",
    "api_irtcengine_setlocalvideomirrormode",
    "api_irtcengine_setremoterendermode2",
    "api_irtcengineex_setremoterendermodeex",
    "api_imediaplayer_setrendermode",
    "api_irtcengine_setuplocalvideo",
    "api_irtcengine_setupremotevideo",
    "api_irtcengineex_setupremotevideoex",
    "api_irtcengine_startmediarenderingtracing",
    "api_irtcengineex_startmediarenderingtracingex",
    "callback_irtcengineeventhandler_onvideorenderingtracingresult",
  ],
  toc_video_raw: [
    "api_imediaengine_unregistervideoframeobserver",
    "callback_imediaplayervideoframeobserver_onframe",
    "api_imediaengine_unregistervideoencodedframeobserver",
    "callback_ivideoframeobserver_getmirrorapplied",
    "callback_ivideoframeobserver_getobservedframeposition",
    "callback_ivideoframeobserver_getrotationapplied",
    "callback_ivideoframeobserver_getvideoformatpreference",
    "callback_ivideoframeobserver_getvideoframeprocessmode",
    "api_imediaengine_registervideoframeobserver",
    "callback_ivideoframeobserver_oncapturevideoframe",
    "callback_ivideoframeobserver_onframe",
    "callback_ivideoframeobserver_onpreencodevideoframe",
    "callback_ivideoframeobserver_onrendervideoframe",
  ],
  toc_video_encoded: [
    "api_imediaengine_removealllisteners",
    "removeListener_IMediaEngine",
    "api_imediaengine_addlistener",
    "api_imediaengine_registervideoencodedframeobserver",
    "callback_ivideoencodedframeobserver_onencodedvideoframereceived",
  ],
  toc_video_custom_capturenrendering: [
    "api_irtcengine_istextureencodesupported",
    "api_irtcengineex_pushencodedvideoimageex",
    "api_irtcengine_pushvideoframe2",
    "api_irtcengine_pushvideoframe3",
    "api_irtcengine_pushvideoframe4",
    "api_irtcengine_createcustomvideotrack",
    "api_irtcengine_destroycustomvideotrack",
    "api_imediaengine_pushvideoframe",
    "api_imediaengine_setexternalvideosource",
  ],
  toc_audio_mixing: [
    "api_irtcengine_adjustaudiomixingplayoutvolume",
    "api_irtcengine_adjustaudiomixingpublishvolume",
    "api_irtcengine_adjustaudiomixingvolume",
    "api_irtcengine_adjustplaybacksignalvolume",
    "api_irtcengine_getaudiomixingcurrentposition",
    "api_irtcengine_getaudiomixingduration",
    "api_irtcengine_getaudiomixingplayoutvolume",
    "api_irtcengine_getaudiomixingpublishvolume",
    "api_irtcengine_getaudiotrackcount",
    "api_irtcengine_pauseaudiomixing",
    "api_irtcengine_resumeaudiomixing",
    "api_irtcengine_selectaudiotrack",
    "api_imediaplayer_selectmultiaudiotrack",
    "api_irtcengine_setaudiomixingdualmonomode",
    "api_irtcengine_setaudiomixingpitch",
    "api_irtcengine_setaudiomixingposition",
    "api_irtcengine_startaudiomixing",
    "api_irtcengine_startaudiomixing2",
    "api_irtcengine_stopaudiomixing",
    "callback_irtcengineeventhandler_onaudiomixingfinished",
    "callback_irtcengineeventhandler_onaudiomixingpositionchanged",
    "callback_irtcengineeventhandler_onaudiomixingstatechanged",
  ],
  toc_audio_effect_file: [
    "api_irtcengine_playeffect2",
    "api_irtcengine_playeffect",
    "api_irtcengine_geteffectcurrentposition",
    "api_irtcengine_geteffectduration",
    "api_irtcengine_geteffectsvolume",
    "api_irtcengine_getvolumeofeffect",
    "api_irtcengine_pausealleffects",
    "api_irtcengine_pauseeffect",
    "api_irtcengine_playalleffects",
    "api_irtcengine_playeffect3",
    "api_irtcengine_preloadeffect",
    "api_irtcengine_resumealleffects",
    "api_irtcengine_resumeeffect",
    "api_irtcengine_seteffectposition",
    "api_irtcengine_seteffectsvolume",
    "api_irtcengine_setvolumeofeffect",
    "api_irtcengine_stopalleffects",
    "api_irtcengine_stopeffect",
    "api_irtcengine_unloadalleffects",
    "api_irtcengine_unloadeffect",
    "callback_irtcengineeventhandler_onaudioeffectfinished",
  ],
  toc_rhythmplayer: [
    "api_irtcengine_configrhythmplayer",
    "api_irtcengine_startrhythmplayer",
    "api_irtcengine_stoprhythmplayer",
    "callback_irtcengineeventhandler_onrhythmplayerstatechanged",
  ],
  toc_mediaplayer_initialize: [
    "api_imediaplayer_dispose",
    "api_imediaplayer_initeventhandler",
    "removeAllListeners_IMediaPlayer",
    "removeListener_IMediaPlayer",
    "addListener_IMediaPlayer",
    "api_irtcengine_createmediaplayer",
    "api_irtcengine_destroymediaplayer",
    "api_getmediaplayercachemanager",
  ],
  toc_mediaplayer_open: [
    "api_imediaplayer_open",
    "api_imediaplayer_open2",
    "api_imediaplayer_openwithcustomsource",
    "api_imediaplayer_openwithmediasource",
    "api_imediaplayer_preloadsrc",
    "api_imediaplayer_switchsrc",
    "api_imediaplayer_unloadsrc",
  ],
  toc_mediaplayer_playnrender: [
    "api_imediaplayer_selectaudiotrack",
    "api_imediaplayer_setaudiodualmonomode",
    "api_imediaplayer_setaudiopitch",
    "api_imediaplayer_setloopcount",
    "api_imediaplayer_setplaybackspeed",
    "api_imediaplayer_setplayeroption",
    "api_imediaplayer_setspatialaudioparams",
    "api_imediaplayer_setview",
  ],
  toc_mediaplayer_control: [
    "api_imusicplayer_stop",
    "api_imediaplayer_adjustplayoutvolume",
    "api_imediaplayer_adjustpublishsignalvolume",
    "api_imediaplayer_mute",
    "api_imediaplayer_pause",
    "api_imediaplayer_play",
    "api_imediaplayer_playpreloadedsrc",
    "api_imediaplayer_resume",
    "api_imediaplayer_seek",
    "api_imediaplayer_stop",
    "callback_imediaplayercustomdataprovider_onseek",
  ],
  toc_mediaplayer_info: [
    "api_imediaplayer_getplaysrc",
    "api_imediaplayer_getduration",
    "api_imediaplayer_getmediaplayerid",
    "api_imediaplayer_getmute",
    "api_imediaplayer_getplayoutvolume",
    "api_imediaplayer_getplayposition",
    "api_imediaplayer_getplaysrc",
    "api_imediaplayer_getpublishsignalvolume",
    "api_imediaplayer_getstate",
    "api_imediaplayer_getstreamcount",
    "api_imediaplayer_getstreaminfo",
    "callback_imediaplayersourceobserver_onplayerplaybackstats",
  ],
  toc_mediaplayer_observer: [
    "api_imediaplayer_registeraudioframeobserver",
    "api_imediaplayer_registeraudioframeobserver2",
    "api_imediaplayer_registerplayersourceobserver",
    "api_imediaplayer_registervideoframeobserver",
    "api_imediaplayer_unregisteraudioframeobserver",
    "api_imediaplayer_unregisterplayersourceobserver",
    "api_imediaplayer_unregistervideoframeobserver",
    "callback_imediaplayersourceobserver_onaudiovolumeindication",
    "callback_iaudiopcmframesink_onframe",
    "callback_imediaplayersourceobserver_onmetadata",
    "callback_imediaplayersourceobserver_onplaybufferupdated",
    "callback_imediaplayersourceobserver_onplayerevent",
    "callback_imediaplayersourceobserver_onplayerinfoupdated",
    "callback_imediaplayersourceobserver_onplayersourcestatechanged",
    "callback_imediaplayersourceobserver_onplayersrcinfochanged",
    "callback_imediaplayersourceobserver_onpositionchanged",
    "callback_imediaplayersourceobserver_onpreloadevent",
    "callback_imediaplayercustomdataprovider_onreaddata",
  ],
  toc_mediaplayer_cache: [
    "api_imediaplayercachemanager_sharedinstance",
    "api_imediaplayercachemanager_enableautoremovecache",
    "api_imediaplayercachemanager_getcachedir",
    "api_imediaplayercachemanager_getcachefilecount",
    "api_imediaplayercachemanager_getmaxcachefilecount",
    "api_imediaplayercachemanager_getmaxcachefilesize",
    "api_imediaplayercachemanager_removeallcaches",
    "api_imediaplayercachemanager_removecachebyuri",
    "api_imediaplayercachemanager_removeoldcache",
    "api_imediaplayercachemanager_setcachedir",
    "api_imediaplayercachemanager_setmaxcachefilecount",
    "api_imediaplayercachemanager_setmaxcachefilesize",
    "callback_imediaplayersourceobserver_onplayercachestats",
  ],
  toc_drm: [
    "api_imusiccontentcenter_destroy",
    "api_imusiccontentcenter_getmusiccollectionbymusicchartid2",
    "api_imusiccontentcenter_searchmusic2",
    "api_imusicplayer_open2",
    "api_imusiccontentcenter_enablemainqueuedispatch",
    "api_irtcengine_getmusiccontentcenter",
    "api_imusiccontentcenter_createmusicplayer",
    "api_imusiccontentcenter_getcaches",
    "api_musiccollection_getcount",
    "api_musicchartcollection_get",
    "api_imusiccontentcenter_getinternalsongcode",
    "api_imusiccontentcenter_getlyric",
    "api_musiccollection_getmusic",
    "api_imusiccontentcenter_getmusiccharts",
    "api_imusiccontentcenter_getmusiccollectionbymusicchartid",
    "api_musiccollection_getpage",
    "api_musiccollection_getpagesize",
    "api_musiccollection_gettotal",
    "api_imusiccontentcenter_getsongsimpleinfo",
    "api_imusiccontentcenter_initialize",
    "api_imusiccontentcenter_ispreloaded",
    "api_imusicontentcenter_preload",
    "api_imusicontentcenter_preload2",
    "api_imusiccontentcenter_registereventhandler",
    "api_imusiccontentcenter_release",
    "api_imusiccontentcenter_removecache",
    "api_imusiccontentcenter_renewtoken",
    "api_imusiccontentcenter_searchmusic",
    "api_imusiccontentcenter_unregistereventhandler",
    "callback_imusiccontentcentereventhandler_onlyricresult",
    "callback_imusiccontentcentereventhandler_onmusicchartsresult",
    "callback_imusiccontentcentereventhandler_onmusiccollectionresult",
    "callback_imusiccontentcentereventhandler_onpreloadevent",
    "callback_imusiccontentcentereventhandler_onsongsimpleinforesult",
    "api_imusicplayer_open",
  ],
  toc_recording: [
    "api_imediarecorder_enablemainqueuedispatch",
    "api_imediarecorder_removelistener",
    "api_imediarecorder_addlistener",
    "api_imediarecorder_removealllisteners",
    "api_irtcengine_createmediarecorder",
    "api_irtcengine_destroymediarecorder",
    "api_imediarecorder_setmediarecorderobserver",
    "api_irtcengine_startaudiorecording",
    "api_irtcengine_startaudiorecording2",
    "api_irtcengine_startaudiorecording3",
    "api_imediarecorder_startrecording",
    "api_irtcengine_stopaudiorecording",
    "api_imediarecorder_stoprecording",
    "callback_imediarecorderobserver_onrecorderinfoupdated",
    "callback_imediarecorderobserver_onrecorderstatechanged",
  ],
  toc_channel_media_relay: [
    "api_irtcengine_startchannelmediarelay",
    "api_irtcengineex_startchannelmediarelayex",
    "api_irtcengine_updatechannelmediarelay",
    "api_irtcengineex_updatechannelmediarelayex",
    "callback_irtcengineeventhandler_onchannelmediarelayevent",
    "api_irtcengine_pauseallchannelmediarelay",
    "api_irtcengineex_pauseallchannelmediarelayex",
    "api_irtcengine_resumeallchannelmediarelay",
    "api_irtcengineex_resumeallchannelmediarelayex",
    "api_irtcengine_startorupdatechannelmediarelay",
    "api_irtcengineex_startorupdatechannelmediarelayex",
    "api_irtcengine_stopchannelmediarelay",
    "api_irtcengineex_stopchannelmediarelayex",
    "callback_irtcengineeventhandler_onchannelmediarelaystatechanged",
  ],
  toc_media_push: [
    "api_irtcengine_addinjectstreamurl",
    "api_irtcengine_removeinjectstreamurl",
    "api_irtcengine_setlivetranscoding",
    "api_irtcengine_startrtmpstreamwithouttranscoding",
    "api_irtcengineex_startrtmpstreamwithouttranscodingex",
    "api_irtcengine_startrtmpstreamwithtranscoding",
    "api_irtcengineex_startrtmpstreamwithtranscodingex",
    "api_irtcengine_stoprtmpstream",
    "api_irtcengineex_stoprtmpstreamex",
    "api_irtcengine_updatertmptranscoding",
    "api_irtcengineex_updatertmptranscodingex",
    "callback_irtcengineeventhandler_onrtmpstreamingevent",
    "callback_irtcengineeventhandler_onrtmpstreamingstatechanged",
    "callback_irtcengineeventhandler_ontranscodingupdated",
  ],
  toc_cdn_streaming: [
    "api_irtcengine_setdirectcdnstreamingaudioconfiguration",
    "api_irtcengine_setdirectcdnstreamingvideoconfiguration",
    "api_irtcengine_startdirectcdnstreaming",
    "api_irtcengine_stopdirectcdnstreaming",
    "callback_idirectcdnstreamingeventhandler_ondirectcdnstreamingstatechanged",
    "callback_idirectcdnstreamingeventhandler_ondirectcdnstreamingstats",
  ],
  toc_datastream: [
    "api_irtcengine_sendmetadata",
    "api_irtcengine_setmaxmetadatasize",
    "api_irtcengine_createdatastream",
    "api_irtcengineex_createdatastreamex",
    "api_irtcengine_createdatastream2",
    "api_irtcengineex_createdatastreamex2",
    "api_irtcengine_sendstreammessage",
    "api_irtcengineex_sendstreammessageex",
    "callback_irtcengineeventhandler_onstreammessage",
    "callback_irtcengineeventhandler_onstreammessageerror",
  ],
  toc_metadata_observer: [
    "api_irtcengine_setmediametadatadatasource",
    "callback_imetadataobserver_getmaxmetadatasize",
    "api_irtcengine_registermediametadataobserver",
    "api_irtcengine_unregistermediametadataobserver",
    "callback_imetadataobserver_onmetadatareceived",
    "callback_imetadataobserver_onreadytosendmetadata",
  ],
  toc_audio_route: [
    "api_irtcengine_isspeakerphoneenabled",
    "api_irtcengine_setdefaultaudioroutetospeakerphone",
    "api_irtcengine_setenablespeakerphone",
    "api_irtcengine_setrouteincommunicationmode",
    "callback_irtcengineeventhandler_onaudioroutingchanged",
  ],
  toc_mobile_camera: [
    "api_irtcengine_enablemulticamera",
    "api_irtcengine_getcameramaxzoomfactor",
    "api_irtcengine_iscameraautoexposurefacemodesupported",
    "api_irtcengine_iscameraautofocusfacemodesupported",
    "api_irtcengine_iscameraexposurepositionsupported",
    "api_irtcengine_iscameraexposuresupported",
    "api_irtcengine_iscamerafacedetectsupported",
    "api_irtcengine_iscamerafocussupported",
    "api_irtcengine_iscameratorchsupported",
    "api_irtcengine_iscamerazoomsupported",
    "api_irtcengine_setcameraautoexposurefacemodeenabled",
    "api_irtcengine_setcameraautofocusfacemodeenabled",
    "api_irtcengine_setcameracapturerconfiguration",
    "api_irtcengine_setcameraexposurefactor",
    "api_irtcengine_setcameraexposureposition",
    "api_irtcengine_setcamerafocuspositioninpreview",
    "api_irtcengine_setcameratorchon",
    "api_irtcengine_setcamerazoomfactor",
    "api_irtcengine_switchcamera",
    "callback_irtcengineeventhandler_oncameraexposureareachanged",
    "callback_irtcengineeventhandler_oncamerafocusareachanged",
    "callback_irtcengineeventhandler_oncameraready",
  ],
  toc_common_device: [
    "api_irtcengine_enumeratedevices",
    "api_irtcengine_getdeviceinfo",
    "api_irtcengine_statechanged",
    "api_irtcengine_setdevicevolume",
    "api_monitordevicechange",
    "api_irtcengine_getdevicevolume",
  ],
  toc_pc_audio_device_management: [
    "api_irtcengine_getaudiodevicemanager",
    "api_iaudiodevicemanager_getplaybackdefaultdevice",
    "api_iaudiodevicemanager_getrecordingdefaultdevice",
    "api_iaudiodevicemanager_enumerateplaybackdevices",
    "api_iaudiodevicemanager_enumeraterecordingdevices",
    "api_iaudiodevicemanager_followsystemloopbackdevice",
    "api_iaudiodevicemanager_followsystemplaybackdevice",
    "api_iaudiodevicemanager_followsystemrecordingdevice",
    "api_iaudiodevicecollection_getapplicationvolume",
    "api_irtcengine_getaudiodeviceinfo",
    "api_iaudiodevicecollection_getcount",
    "api_iaudiodevicecollection_getdefaultdevice",
    "api_iaudiodevicecollection_getdevice",
    "api_iaudiodevicemanager_getloopbackdevice",
    "api_iaudiodevicemanager_getplaybackdevice",
    "api_iaudiodevicemanager_getplaybackdeviceinfo",
    "api_iaudiodevicemanager_getplaybackdevicemute",
    "api_iaudiodevicemanager_getplaybackdevicevolume",
    "api_iaudiodevicemanager_getrecordingdevice",
    "api_iaudiodevicemanager_getrecordingdeviceinfo",
    "api_iaudiodevicemanager_getrecordingdevicevolume",
    "api_iaudiodevicecollection_isapplicationmute",
    "api_iaudiodevicecollection_release",
    "api_iaudiodevicemanager_release",
    "api_iaudiodevicecollection_setapplicationmute",
    "api_iaudiodevicecollection_setapplicationvolume",
    "api_iaudiodevicecollection_setdevice",
    "api_iaudiodevicemanager_setloopbackdevice",
    "api_iaudiodevicemanager_setplaybackdevice",
    "api_iaudiodevicemanager_setplaybackdevicemute",
    "api_iaudiodevicemanager_setplaybackdevicevolume",
    "api_iaudiodevicemanager_setrecordingdevice",
    "api_iaudiodevicemanager_setrecordingdevicevolume",
    "api_iaudiodevicemanager_startaudiodeviceloopbacktest",
    "api_iaudiodevicemanager_startplaybackdevicetest",
    "api_iaudiodevicemanager_startrecordingdevicetest",
    "api_iaudiodevicemanager_stopaudiodeviceloopbacktest",
    "api_iaudiodevicemanager_stopplaybackdevicetest",
    "api_iaudiodevicemanager_stoprecordingdevicetest",
    "callback_irtcengineeventhandler_onaudiodevicestatechanged",
    "callback_irtcengineeventhandler_onaudiodevicevolumechanged",
  ],
  toc_pc_video_device_management: [
    "api_irtcengine_getvideodevicemanager",
    "api_ivideodevicemanager_enumeratevideodevices",
    "api_ivideodevicemanager_getcapability",
    "callback_irtcengineeventhandler_onvideodevicestatechanged",
    "api_ivideodevicecollection_getcount",
    "api_ivideodevicecollection_getdevice",
    "api_ivideodevicemanager_getdevice",
    "api_ivideodevicemanager_numberofcapabilities",
    "api_irtcengine_querycodeccapability",
    "api_ivideodevicecollection_release",
    "api_ivideodevicemanager_release",
    "api_irtcengine_setcameradeviceorientation",
    "api_ivideodevicecollection_setdevice",
    "api_ivideodevicemanager_setdevice",
  ],
  toc_extension: [
    "api_irtcengine_getextensionproperty",
    "api_irtcengine_enableextension",
    "api_irtcengine_getextensionproperty2",
    "api_irtcengine_loadextensionprovider",
    "api_irtcengine_registerextension",
    "api_irtcengine_setextensionproperty",
    "api_irtcengine_setextensionproviderproperty",
    "callback_irtcengineeventhandler_onextensionerror",
    "callback_irtcengineeventhandler_onextensionevent",
    "callback_irtcengineeventhandler_onextensionstarted",
    "callback_irtcengineeventhandler_onextensionstopped",
  ],
  toc_network: [
    "api_irtcengine_getnativehandle",
    "api_irtcengine_enablemainqueuedispatch",
    "api_rtcengineext_getassetabsolutepath",
    "api_irtcengine_setlocalpublishfallbackoption",
    "api_irtcengine_complain",
    "api_irtcengine_enableencryption",
    "api_irtcengine_enablewebsdkinteroperability",
    "api_irtcengine_getcallid",
    "api_irtcengine_getconnectionstate",
    "api_irtcengineex_getconnectionstateex",
    "api_irtcengine_getcurrentmonotonictimeinms",
    "api_irtcengine_geterrordescription",
    "api_irtcengine_getnetworktype",
    "api_irtcengine_getntpwalltimeinms",
    "api_irtcengine_getversion",
    "api_irtcengine_isfeatureavailableondevice",
    "callback_irtcengineeventhandler_onremotesubscribefallbacktoaudioonly",
    "api_irtcengine_querydevicescore",
    "api_irtcengine_queryinterface",
    "api_irtcengine_rate",
    "api_irtcengine_registerpacketobserverionerror",
    "callback_irtcengineeventhandler_onproxyconnected",
    "callback_ipacketobserver_onreceiveaudiopacket",
    "callback_ipacketobserver_onreceivevideopacket",
    "callback_ipacketobserver_onsendaudiopacket",
    "callback_ipacketobserver_onsendvideopacket",
    "callback_irtcengineeventhandler_onuplinknetworkinfoupdated",
  ],
};

function generateNewLink(
  originalLink: string,
  filename: string,
  platform: string
) {
  let isClassOrEnum =
    filename.startsWith("class_") || filename.startsWith("enum_");
  if (isClassOrEnum) {
    return `/api-ref/rtc/${platform}/API/${filename}`;
  }

  const currentToc = Object.entries(tocList).find(([_toc, list]) =>
    list.includes(filename)
  );
  if (currentToc) {
    return `/api-ref/rtc/${platform}/API/${currentToc[0]}#${filename}`;
  }

  return originalLink;
}

function adjustFormat(text: string) {
  return text
    .replace(/(\s\[\d\/\d\\\])(\]\(\/api-ref\/rtc.*?\))/g, '$2$1')
    .replace(/\s(\[\d\/\d)\\\]/g, '$1]')
    .replace(/\[([^\[\]\/]*?)\](?=\(\/api-ref\/rtc)/g, '[`$1`]');
}

export function replaceRtcApiLink(inputText: string, platform: string) {
  let outputText = inputText.replace(
    /API\/(.+?)\.html/g,
    (match, filename) => {
      return generateNewLink(match, filename, platform);
    }
  );

  outputText = adjustFormat(outputText);

  return outputText;
}
